import { Event, FAQ } from "@/lib/types";

export const mockEvents: Event[] = [
  {
    id: "evt-001",
    slug: "midnight-canvas-live",
    title: "Midnight Canvas Live",
    date: "2026-05-14",
    time: "20:00",
    location: "Brooklyn Sound Hall, New York",
    price: 78,
    category: "music",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80",
    description: "A neon-soaked indie set with immersive visuals and guest performers.",
    capacity: 1200,
    soldTickets: 970,
    ratings: 4.7,
    reviews: [
      { id: "r-1", rating: 5, comment: "Best live mix this year.", author: "K. Moore", date: "2026-03-03" },
    ],
    seatingType: "mixed",
  },
  {
    id: "evt-002",
    slug: "city-rivals-final",
    title: "City Rivals Final",
    date: "2026-06-02",
    time: "19:30",
    location: "Harbor Arena, Boston",
    price: 120,
    category: "sports",
    image: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=80",
    description: "A championship showdown with pre-game fan zones and post-game lights.",
    capacity: 18000,
    soldTickets: 17220,
    ratings: 4.8,
    reviews: [
      { id: "r-2", rating: 5, comment: "Electric atmosphere.", author: "L. Ortiz", date: "2026-03-10" },
    ],
    seatingType: "assigned",
  },
  {
    id: "evt-003",
    slug: "fractured-mirror",
    title: "Fractured Mirror",
    date: "2026-05-28",
    time: "18:30",
    location: "West End Stage, Chicago",
    price: 64,
    category: "theater",
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1200&q=80",
    description: "A contemporary drama exploring memory, family, and second chances.",
    capacity: 750,
    soldTickets: 620,
    ratings: 4.6,
    reviews: [
      { id: "r-3", rating: 4, comment: "Strong cast and staging.", author: "M. Singh", date: "2026-02-22" },
    ],
    seatingType: "assigned",
  },
  {
    id: "evt-004",
    slug: "future-build-summit",
    title: "Future Build Summit",
    date: "2026-09-09",
    time: "09:00",
    location: "Civic Convention Center, Seattle",
    price: 249,
    category: "conference",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    description: "Product, AI, and design leaders sharing practical playbooks.",
    capacity: 5000,
    soldTickets: 3980,
    ratings: 4.5,
    reviews: [
      { id: "r-4", rating: 4, comment: "Useful sessions, zero fluff.", author: "N. Brooks", date: "2026-03-15" },
    ],
    seatingType: "assigned",
  },
  {
    id: "evt-005",
    slug: "shoreline-summer-fest",
    title: "Shoreline Summer Fest",
    date: "2026-07-18",
    time: "13:00",
    location: "Pier Park, San Diego",
    price: 55,
    category: "festival",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80",
    description: "Two stages, food trucks, sunset sets, and beachfront art installations.",
    capacity: 15000,
    soldTickets: 14230,
    ratings: 4.8,
    reviews: [
      { id: "r-5", rating: 5, comment: "Perfect summer vibe.", author: "A. Reed", date: "2026-03-19" },
    ],
    seatingType: "general",
  },
  {
    id: "evt-006",
    slug: "candlelight-strings",
    title: "Candlelight Strings",
    date: "2026-04-25",
    time: "21:00",
    location: "Old Union Hall, Philadelphia",
    price: 42,
    category: "music",
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1200&q=80",
    description: "An intimate orchestral set inside a historic venue.",
    capacity: 400,
    soldTickets: 350,
    ratings: 4.4,
    reviews: [
      { id: "r-6", rating: 4, comment: "Lovely and atmospheric.", author: "T. Vale", date: "2026-03-05" },
    ],
    seatingType: "assigned",
  },
];

export const mockFaqs: FAQ[] = [
  {
    question: "How do I book tickets?",
    answer: "Open an event, choose quantity, and continue to checkout.",
  },
  {
    question: "Can I save events for later?",
    answer: "Yes. Saved events are planned for the account area in the next phase.",
  },
  {
    question: "Are fees included in the price?",
    answer: "The listing shows base ticket price. Checkout will include any additional fees.",
  },
];
